name: "Abhijith's iOS CI Runner 😀"

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  build-and-test:
    name: Build and Run Unit Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode 16.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Show Xcode path
        run: xcode-select -p

      - name: Build and test
        run: |
          xcodebuild \
            -project JenTest.xcodeproj \
            -scheme JenTest \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=Any iOS Simulator Device' \
            clean test
