name: iOS CI — macos-14

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-14          # Apple-silicon runner
    timeout-minutes: 30

    steps:
      # 1. Fetch code
      - uses: actions/checkout@v4

      # 2. Select an Xcode that still bundles an iOS runtime
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'   # ⇠ iOS 17.x simulator included

      # 3. Build the app and run all unit tests
      - name: Build & Test
        run: |
          set -o pipefail
          xcodebuild \
            -project JenTest.xcodeproj \
            -scheme JenTest \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            clean test

      # 4. Always keep the xcresult bundle for inspection
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: XCResult
          path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
