name: iOS CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-14           # or macos-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    # Optional: pin exact Xcode (e.g. 16.2)
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    # Show environment for easier debugging
    - name: Show Xcode version
      run: xcodebuild -version

    # Cache DerivedData to speed up subsequent runs
    - uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-derived-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-derived-

    # Build & run tests on iOS simulator
    - name: Build and Test
      run: |
        xcodebuild \
          -workspace JenTest.xcworkspace \
          -scheme JenTest \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
          clean test | xcbeautify

    # Upload the xcresult bundle as an artifact
    - uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
