name: iOS CI / Run Unit Tests

# Triggers on pull requests to main and pushes to feature branches
on:
  pull_request:
    branches: [main]
  push:
    branches: ['feature/**']

# Auto-cancel redundant workflow runs
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: macos-15-xlarge  # Apple Silicon runner
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      
      # Set up Xcode version
      - uses: maxim-lobanov/setup-xcode@v4
        with:
          xcode-version: '16.4'
      
      # Cache dependencies
      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: ~/.swiftpm
          key: spm-${{ runner.os }}-${{ hashFiles('**/Package.resolved') }}
      
      # Run tests
      - name: Run unit tests
        run: |
          set -euo pipefail
          xcodebuild \
            -scheme "JenTest" \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=18.0" \
            -testPlan UnitTests \
            test | xcpretty && exit ${PIPESTATUS[0]}
      
      # Upload logs if tests fail
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: TestLogs
          path: ~/Library/Logs/DiagnosticReports/*.crash
